import { generateObject } from "ai";
import { z } from "zod";
import { resolvePersonaModel } from "./personaModel.js";
import { generatePersonaBehavior } from "./personaBehaviorGen.js";
import { generatePersonaRawSeed } from "./personaRawSeed.js";

// Appendix D — persona zod schema. Stored verbatim in `personas.data`.
export const PersonaSchema = z.object({
  fullName: z.string(),
  role: z.string(),
  industry: z.string(),
  geo: z.string(),
  /** LinkedIn location — city/region/country; used on signup and in backstory. */
  location: z.string(),
  backstory: z.string().max(1200),
  tone: z.string(),
  interests: z.array(z.string()).min(3).max(8),
  behavior: z.object({
    timezone: z.string(),
    activeHours: z
      .array(
        z.object({
          start: z.number().min(0).max(23),
          end: z.number().min(1).max(24),
        }),
      )
      .min(1)
      .max(3),
    weekdayActivity: z.array(z.number().min(0).max(1)).length(7),
    sessionsPerDay: z.object({ min: z.number().min(0), max: z.number().max(6) }),
    actionMix: z.object({
      warmup_feed: z.number(),
      engage_post: z.number(),
      send_invitation: z.number(),
      send_message: z.number(),
      fetch_profile: z.number(),
    }),
  }),
});

export type Persona = z.infer<typeof PersonaSchema>;

/** Narrative fields the LLM flattens from Faker seed data for LinkedIn. */
const PersonaNarrativeSchema = z.object({
  role: z.string(),
  industry: z.string(),
  backstory: z.string().max(1200),
  tone: z.string(),
  interests: z.array(z.string()).min(3).max(8),
});

export async function generatePersona(input: {
  seed: string;
  geo: string;
  timezone: string;
  roleArchetype: string;
  /** Override Faker city — e.g. "Frankfurt, Hesse, Germany". */
  location?: string;
  model?: string;
  userPrompt?: string;
}): Promise<Persona> {
  const raw = generatePersonaRawSeed({
    seed: input.seed,
    geo: input.geo,
    roleArchetype: input.roleArchetype,
  });
  const behavior = generatePersonaBehavior({ seed: input.seed, timezone: input.timezone });
  const location = input.location?.trim() || raw.location;

  const lines = [
    `You are flattening seeded profile ingredients into one coherent LinkedIn persona.`,
    `The raw facts below were generated by Faker (locale-matched to geo). Use them as ground truth — do not invent a different name, employer, or city.`,
    ``,
    `Raw seed (JSON):`,
    JSON.stringify(raw, null, 2),
    ``,
    `Hard constraints:`,
    `- fullName is already "${raw.fullName}" — do not change it`,
    `- geo must be exactly "${input.geo}" (country code only — not the LinkedIn location field)`,
    `- location is already "${location}" — the backstory MUST place the persona in this exact city/region; do not substitute another city`,
    `- when LinkedIn asks for location during onboarding, this persona lives in: ${location}`,
    `- role archetype hint from operator: "${input.roleArchetype}" — align the LinkedIn headline (role field) with this while staying plausible given the Faker job data`,
    `- backstory: max 1200 characters, first person, grounded and unremarkable (no extraordinary claims)`,
    `- weave in company, location, years of experience, and prior employer naturally`,
    `- interests: 3–8 items suitable for a LinkedIn profile (flatten music/book/topic seeds into human hobbies or professional interests; drop nonsense words)`,
    `- tone: short phrase describing how they write on LinkedIn (e.g. "measured and curious", "direct and pragmatic")`,
    `- industry: one concise LinkedIn-style industry label inferred from the seed`,
  ];
  if (input.userPrompt?.trim()) {
    lines.push(
      ``,
      `Additional creative direction from the operator (incorporate naturally, do not contradict geo or the seeded name/location):`,
      input.userPrompt.trim(),
    );
  }

  const { object: narrative } = await generateObject({
    model: resolvePersonaModel(input.model),
    schema: PersonaNarrativeSchema,
    prompt: lines.join("\n"),
    allowSystemInMessages: true,
  });

  return PersonaSchema.parse({
    fullName: raw.fullName,
    geo: input.geo,
    location,
    ...narrative,
    behavior,
  });
}
